import Head from 'next/head'
import Link from 'next/link'
import Layout from '../../components/layout'

import PostStyles from '../../styles/Post.module.scss'
import styles from '../../styles/Home.module.css'

export default function FirstPost() {
    return (
        <Layout>
            <Head>
                <title>gridbase® studio | Blog </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.main}>
                <h1 className={styles.title}>First Post</h1>
                <Link href="/">
                    <a className={PostStyles.homepageLink}>Back Home</a>
                </Link>
            </div>

        </Layout>
    )
}
