import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/index.module.scss'

export default function Home() {
  return (
    <div className={styles.mainHero}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.leftTextHero}>
        <h1 className={styles.titleLarge}>Well crafted</h1>
        <div className={styles.innerParagraphContainer}>
          <p className="universalPAG">We're helping you define your brand's identity, and build an immersive experience around it.</p>
          <p className={styles.universalPAG}>We provide a seamless flow of ideas in the fields of web design, creative direction, photography and videography.</p>
        </div>
      </div>
    </div>
  )
}
